# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: docshub-back
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10

package:
  individually: true
  patterns:
    - "!**/**"
    - "utils/**"

functions:
  add_user_to_group:
    handler: add_user_to_group/handler.add_user_to_group
    package:
      include: "add_user_to_group/**"
  get_file_metadata:
    handler: get_file_metadata/handler.get_file_metadata
    package:
      include: "get_file_metadata/**"
      events:
        - http:
            path: /api/get_file_metadata/{key}
            method: get
            cors: true
            request:
              parameters:
                paths:
                  key: true
  upload_file:
    handler: upload_file/handler.upload_file
    package:
      include: "upload_file/**"
      events:
        - http:
            path: /api/upload-file
            method: post
            cors: true
  download_file:
    handler: download_file/handler.download_file
    package:
      include: "download_file/**"
      events:
        - http:
            path: /api/download-file
            method: get
            cors: true
  upload_error_handling:
    handler: upload_error_handling/handler.handle_error
    package:
      include: "upload_error_handling/**"
    # events:
    #   - http:
    #       path: /api/download-file
    #       method: get
    #       cors: true
  upload_file_s3:
    handler: upload_file_s3/handler.upload_file_s3
    package:
      include: "upload_file_s3/**"
    # events:
    #   - http:
    #       path: /api/download-file
    #       method: get
    #       cors: true
  upload_validation:
    handler: upload_validation/handler.validate
    package:
      include: "upload_validation/**"
  upload_success_handling:
    handler: upload_success_handling/handler.handle_success
    package:
      include: "upload_success_handling/**"
      # events:
      #   - http:
      #       path: /api/download-file
      #       method: get
      #       cors: true
  get_file_s3:
    handler: get_file_s3/handler.get_file_s3
    package:
      include: "get_file_s3/**"
  mailing:
    handler: mailing/handler.send_email
    package:
      include: "mailing/**"
  on_file_change:
    handler: on_file_change/handler.on_change
    package:
      include: "on_file_change/**"
  delete_file:
    handler: delete_file/handler.delete_file
    package:
      include: "delete_file/**"
      events:
        - http:
            path: /api/delete-file
            method: delete
            cors: true
  update_file:
    handler: update_file/handler.update_file
    package:
      include: "update_file/**"
  create_album:
    handler: create_album/handler.create_album
    package:
      include: "create_album/**"
      events:
        - http:
            path: /api/create_album
            method: post
            cors: true
  delete_album:
    handler: delete_album/handler.delete_album
    package:
      include: "delete_album/**"
      events:
        - http:
            path: /api/delete_album
            method: delete
            cors: true
  get_users_with_access:
    handler: get_users_with_access/handler.get_users_with_access
    package:
      include: "get_users_with_access/**"
      events:
        - http:
            path: /api/get-users-with-access
            method: get
            cors: true
  add_user_access:
    handler: add_user_access/handler.add_user_access
    package:
      include: "add_user_access/**"
      events:
        - http:
            path: /api/add-user-access
            method: post
            cors: true
  remove_user_access:
    handler: remove_user_access/handler.remove_user_access
    package:
      include: "remove_user_access/**"
      events:
        - http:
            path: /api/remove-user-access
            method: delete
            cors: true
  get_user_access:
    handler: get_user_access/handler.get_user_access
    package:
      include: "get_user_access/**"
      events:
        - http:
            path: /api/get-user-access
            method: get
            cors: true
